name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/10 * * * *"
  push:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 461e5a7811250f396cd04f3940be994e
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
